services:
  php-fpm:
    image: php:8.4-fpm-alpine
    working_dir: /app
    volumes: [ "../api:/app" ]
    environment:
      APP_ENV: dev
      DB_DSN: "pgsql:host=postgres;port=5432;dbname=app"
      DB_USER: app
      DB_PASS: app
      REDIS_URL: "redis://redis:6379"
    depends_on: [ postgres, redis ]

  nginx:
    image: nginx:alpine
    depends_on: [ php-fpm ]
    ports: [ "8080:80" ]
    volumes:
      - "../api:/app"
      - "./nginx.conf:/etc/nginx/conf.d/default.conf:ro"

  worker:
    image: php:8.4-cli-alpine
    working_dir: /app
    command: ["php", "worker/worker.php"]
    volumes: [ "../api:/app" ]
    environment:
      APP_ENV: dev
      DB_DSN: "pgsql:host=postgres;port=5432;dbname=app"
      DB_USER: app
      DB_PASS: app
      REDIS_URL: "redis://redis:6379"
    depends_on: [ postgres, redis ]

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
    ports: [ "5432:5432" ]
    volumes:
      - "pgdata:/var/lib/postgresql/data"
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql:ro"

  redis:
    image: redis:alpine
    ports: [ "6379:6379" ]

volumes:
  pgdata:
