name: ci
on: [push, pull_request]

jobs:
  php:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['8.3', '8.4']
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with: { php-version: ${{ matrix.php }}, coverage: none }
      - name: Install deps
        working-directory: api
        run: |
          composer install --no-interaction --prefer-dist
      - name: Static analysis
        working-directory: api
        run: composer stan
      - name: Tests
        working-directory: api
        run: composer test
